In [22]:
import pandas as pd
from xml.etree import ElementTree as et
from lxml import objectify
from tqdm.notebook import tqdm
from update_data import update_data

In [23]:
update_data()

In [3]:
df_annuel = pd.read_xml("data/PrixCarburants_annuel_2022.xml")

In [13]:
xml_data = objectify.parse('data/PrixCarburants_instantane.xml')  # Parse XML data
pvd_list = xml_data.getroot()  # Root element
record = []

for pdv in pvd_list.getchildren():
    new_row = {}
    attrib_pdv = pdv.attrib
    new_row["id"] = attrib_pdv["id"]
    new_row["latitude"] = float(attrib_pdv["latitude"])/100000
    new_row["longitude"] = float(attrib_pdv["longitude"])/100000
    new_row["cp"] = attrib_pdv["cp"]
    new_row["pop"] = attrib_pdv["pop"]
    new_row["adresse"] = pdv.adresse.text
    new_row["ville"] = pdv.ville.text
    if hasattr(pdv, 'prix'):
        for prix in pdv.prix:
            attrib_prix = prix.attrib
            nom = attrib_prix["nom"]
            new_row[f"maj_{nom}"] = attrib_prix["maj"]
            new_row[f"prix_{nom}"] = attrib_prix["valeur"]
    record.append(new_row)

df_instant = pd.DataFrame.from_records(record)
df_instant.to_csv("test.csv")

In [21]:
for index, row in df_instant.iterrows():
    print(row["latitude"])
    break

50.594774550000004

In [9]:
df_instant[df_instant["cp"] == "91300"]

,id,latitude,longitude,cp,pop,adresse,ville,maj_Gazole,prix_Gazole,maj_E85,prix_E85,maj_E10,prix_E10,maj_SP98,prix_SP98,maj_GPLc,prix_GPLc,maj_SP95,prix_SP95
1855,91300018,4872.260000,226.213000,91300,R,180 RUE DE PARIS,MASSY,2022-03-11 00:01:00,2.229,2022-03-11 00:01:00,0.859,2022-03-11 00:01:00,2.135,2022-03-11 00:01:00,2.245,NaN,NaN,NaN,NaN
1859,91300020,4872.852000,224.518000,91300,R,40 ROUTE DE PALAISEAU,MASSY,2022-03-11 00:01:00,2.139,2022-03-11 00:01:00,0.859,2022-03-11 00:01:00,2.022,2022-03-11 00:01:00,2.112,NaN,NaN,NaN,NaN
2138,91300022,4873.100000,224.200000,91300,R,VOIE EXPRESS CD 117,Massy,2022-03-10 16:55:00,2.349,2022-01-28 11:00:00,0.899,2022-03-09 17:10:00,2.229,2022-03-09 17:10:00,2.349,2022-01-12 12:30:00,0.929,NaN,NaN
3441,91300007,4872.600000,228.000000,91300,R,Avenue de l'Europe,Massy,2022-03-11 08:05:10,2.149,NaN,NaN,2022-03-11 08:05:11,2.069,2022-03-11 08:05:11,2.159,2022-03-11 08:05:11,1.049,2022-03-11 08:05:11,2.139
6733,91300019,4873.949918,230.178007,91300,R,190 AVENUE DU GENERAL LECLERC,MASSY,2022-03-11 00:01:00,2.137,NaN,NaN,2022-03-11 00:01:00,2.025,2022-03-11 00:01:00,2.142,2022-03-11 00:01:00,0.934,NaN,NaN
8992,91300006,4872.900000,224.500000,91300,R,Route de Palaiseau,MASSY,2022-03-11 07:49:30,2.100,NaN,NaN,2022-03-11 07:49:31,2.019,2022-03-11 07:49:31,2.099,NaN,NaN,2022-03-11 07:49:30,2.070